# docker-compose up (docker-compose down).
# podman-compose up (podman-compose down)

services:
  db:
    image: postgres:15.1-alpine
    container_name: PostgreSQL
    restart: on-failure
    # Privileged para evitar o erro: '/var/lib/postgresql/data': Permission denied
    privileged: true
    ports:
      - '5432:5432'
    volumes:
      - ../database/postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: database_name
